# Site settings
title: Coding with Heidi
header-img: img/home-bg.png
email: hengstrom25@gmail.com
copyright_name: hengstrom25
description: > # this means to ignore newlines until "baseurl:"
  A blog about my journey in the land of code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  hengstrom25
learn_profile: hengstrom25
email_username: hengstrom25@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
